apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: word-picker
parameters:
- name: APP_NAME
  description: The resource name used for the word piclker deployment, svc, and the apps label
  value: word-picker
  required: false
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  data:
    custom_options.txt: |
      first-word
      second-word
      third-word
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${APP_NAME}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
        - name: word-picker
          image: tinmancoding/word-picker:v2025.2
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          volumeMounts:
          - name: options-config-configmap
            mountPath: /code/config
          env:
          - name: OPTIONS_FILE
            value: /code/config/custom_options.txt
        volumes:
        - name: options-config-configmap
          configMap:
            name: ${APP_NAME}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP